#!/bin/bash -e

echo "Setting up prerequisites"

./script/concerns/linux/setup-openssl &>>./log/setup.log
./script/concerns/linux/setup-docker &>>./log/setup.log

echo "Setting up Nosia"

# Set environment variables for Nosia
./script/concerns/setup-env &>./log/setup.log

# Build Nosia
newgrp docker <<EOF
  docker compose --env-file .env build &>>./log/setup.log
EOF
