#!/bin/bash

echo "Setting up prerequisites"

# Install brew if not installed
if ! command -v brew &>/dev/null; then
  echo "Installing Homebrew"
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sh &>./log/setup.log
fi

# Install openssl if not installed
if ! brew list openssl &>/dev/null; then
  echo "Installing OpenSSL"
  brew install openssl &>./log/setup.log
fi

# Install Docker Desktop if not installed
if ! brew list docker-desktop &>/dev/null; then
  echo "Installing Docker Desktop"
  brew install --cask docker-desktop
fi

echo "Setting up Nosia"

# Start Docker Desktop
open -a Docker
while ! docker system info >/dev/null 2>&1; do
  echo "Waiting for Docker to start..."
  sleep 1
done

# Set environment variables for Nosia
./script/concerns/setup-env &>./log/setup.log

# Build Nosia
echo "Building Nosia"
docker compose --env-file .env build &>./log/setup.log
