#!/bin/bash -e

if ! command -v ollama &>/dev/null; then
  echo "ollama is not installed"
  exit 0
fi

if [ -n "$LLM_MODEL" ]; then
  ollama pull $LLM_MODEL
else
  ollama pull granite3.3:2b
fi
ollama pull granite-embedding:278m
ollama pull granite3-guardian:2b
